@startuml
start
:Действия Пользователя;
fork
  :Просмотр данных по цветам;
  :Запрос данных по складу через браузер;
  :Браузер - Запрос данных в приложении;
  :Приложение - просмотр записей в БД;
fork again
  :Удаление данных по цветам;
  :Пользователь в Браузере указывает количество цветов для удаления;
  :Браузер - передаёт данные для удаления в приложение;
  :Приложение - удаляет данные в БД;
fork again
  :Добавление данных по цветам;
  :Пользователь в Браузере указывает какое количество цветов надо добавить;
  :Браузер - передаёт данных по цветам которые нужно добавить;
  :Приложение - записывает данные в БД;
end fork
:Приложение - передача данных в Браузер;
:Браузер - отображение данных Пользователю;
stop
@enduml