@startuml

actor Sellers

node "Корпоративный ПК" {
  component "Браузер" as Web
}

node "Приложение Цветочный Магазин" {
  component "Frontend" as App
  component "Backend" as Back
  App -ri0)- Back: Interface JDBC
}

Sellers -down-> Web
Web <-down-> App : Interface HTTPS

@enduml